### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by yeled** [dctucker/octoterm#7]
**debug.log**
```
storage: Reading "options" from storage
storage: Reading "options" from storage
storage: Reading "options" from storage
storage: Reading "options" from storage
AgendaView: Loading from local storage
storage: Reading "stars" from storage
storage: Reading "tree" from storage
Bar: Reload -> AgendaView.reload()
AgendaView: Loading...
storage: Reading "stars" from storage
Agenda: Loading notifications from REST API
storage: Writing "notifications" to storage
Agenda: Loaded notifications, building agenda
storage: Writing "agenda" to storage
Agenda: Agenda built, generating GraphQL query
storage: Writing "graphql" to storage
Agenda: Requesting from GraphQL API
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at foreach (/Users/yeled/src/gh/octoterm/components/helpers.js:30:39)
    at foreach (/Users/yeled/src/gh/octoterm/components/api.js:120:4)
    at foreach (/Users/yeled/src/gh/octoterm/components/helpers.js:31:4)
    at graphql.then (/Users/yeled/src/gh/octoterm/components/api.js:119:3)
    at process._tickCallback (internal/process/next_tick.js:68:7)
AgendaView: Loading from local storage
storage: Reading "stars" from storage
storage: Reading "tree" from storage
```

Which json can I share with you privately to debug this?

**Comment by dctucker** [comment]
It looks like the call to graphql is failing. Could you send me `notifications.json` and `graphql.json`?

**Comment by yeled** [comment]
pm'd you the gists on Slack :)

**Comment by dctucker** [comment]
Ok, I've pushed up 43d9f14980830f6a692223ed88e8177d38ff1106 (on `master`) which should help us track down the exact error that is occurring.

**Comment by yeled** [comment]
```
storage: Reading "options" from storage
storage: Reading "options" from storage
storage: Reading "options" from storage
AgendaView: Loading from local storage
storage: Reading "stars" from storage
storage: Reading "tree" from storage
Bar: Reload -> AgendaView.reload()
AgendaView: Loading...
storage: Reading "stars" from storage
Agenda: Loading notifications from REST API
storage: Writing "notifications" to storage
Agenda: Loaded notifications, building agenda
storage: Writing "agenda" to storage
Agenda: Agenda built, generating GraphQL query
storage: Writing "graphql" to storage
Agenda: Requesting from GraphQL API
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at foreach (/Users/yeled/src/gh/octoterm/components/helpers.js:41:39)
    at foreach (/Users/yeled/src/gh/octoterm/components/api.js:151:4)
    at foreach (/Users/yeled/src/gh/octoterm/components/helpers.js:42:4)
    at graphql.then (/Users/yeled/src/gh/octoterm/components/api.js:150:3)
    at process._tickCallback (internal/process/next_tick.js:68:7)
AgendaView: Loading from local storage
storage: Reading "stars" from storage
storage: Reading "tree" from storage
Bar: Quit -> AgendaView.quit()
```

I’m sorry it didn’t do what you expect.

**Comment by yeled** [comment]
Figured it out! I didn't have SSO enabled on the token.
